version: '3.9'
services:
  bzb:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      #DB_HOST: mongodb
      #DB_PORT: 27017
      #DB_USER: ${DB_USER}
      #DB_PASSWORD: ${DB_PASSWORD}
      #DB_NAME: ${DB_NAME}
      #MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      #MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "8080:8080"
      - "8081:8081"

  mongodb:
    image: mongo:latest
    environment:
      #MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      #MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"